// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Data.Concrete;

#nullable disable

namespace StoreApp.Web.Migrations
{
    [DbContext(typeof(StoreDBContext))]
    partial class StoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoreApp.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Telefon",
                            Description = "128 gb",
                            Name = "Samsung S20 FE",
                            Price = 10000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Telefon",
                            Description = "128 gb",
                            Name = "Samsung S21 FE",
                            Price = 20000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Telefon",
                            Description = "256 gb",
                            Name = "Samsung S22 FE",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Telefon",
                            Description = "256 gb",
                            Name = "Samsung S23 FE",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Telefon",
                            Description = "256 gb",
                            Name = "Samsung S24 FE",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Telefon",
                            Description = "1000 gb",
                            Name = "Samsung S25 FE",
                            Price = 40000m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Telefon",
                            Description = "1000 gb",
                            Name = "Samsung S26 FE",
                            Price = 45000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
